image: "swift:5.1"

stages:
  - test
  - deploy

before_script:
  - apt-get update && apt-get install -y libopus-dev libsodium-dev libcairo2-dev

test:
  stage: test
  script:
    - swift test

deploy:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - cd Scripts/setup-d2local && docker build -t setup-d2local . && cd ../..
    - env | sed -n '/^D2_/p' > .env
    - docker run --env-file .env --rm -v d2local:/d2/local setup-d2local
    - docker-compose build
    - docker-compose up -d
