image: "swift:5.1"

stages:
  - test
  - deploy

# before_script:
#   - apt-get update && apt-get install libopus-dev libsodium-dev libcairo2-dev

# test:
#   stage: test
#   script:
#     - swift test

deploy:
  image:
    name: docker/compose:1.24.1
    entrypoint: ["/bin/sh", "-c"]
  stage: deploy
  script:
    - docker-compose build
    - docker-compose up -d
