language: generic
sudo: required
dist: trusty
osx_image: xcode10.2
env:
  - SWIFT_VERSION=https://swift.org/builds/swift-5.0-release/ubuntu1404/swift-5.0-RELEASE/swift-5.0-RELEASE-ubuntu14.04.tar.gz
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
jobs:
  include:
    - stage: build
      name: "D2 build"
      os:
        - linux
        - osx
      script:
        - swift build
    - stage: tests
      name: "D2 tests"
      script:
        - swift test
