language: generic
sudo: required
dist: xenial
osx_image: xcode10.2
env: SWIFT_VERSION=5.0
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap vapor/tap && brew install opus libsodium ctls; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libopus-dev libsodium-dev libcairo2-dev; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"; fi
jobs:
  include:
    - stage: build
      name: "D2 build (Linux)"
      os: linux
      script: swift build
    - name: "D2 build (macOS)"
      os: osx
      script: swift build
    - stage: tests
      name: "D2 tests"
      script: swift test
