language: generic
sudo: required
dist: trusty
osx_image: xcode10.2
env: SWIFT_VERSION=5.0
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
jobs:
  include:
    - stage: build
      name: "D2 build (Linux)"
      os: linux
      script: swift build
    - name: "D2 build (macOS)"
      os: osx
      script: swift build
    - stage: tests
      name: "D2 tests"
      script: swift test
