name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install APT dependencies
      run: sudo apt-get install libopus-dev libsodium-dev libcairo2-dev
    - name: Install Swiftenv
      env:
        swift_version: 5.0
      run: |
        git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
    - name: Install Swift
      env:
        swiftenv_root: $HOME/.swiftenv
      run: $SWIFTENV_ROOT/bin/swiftenv install -s
    - name: Build
      run: |
        echo "Building under Swift $SWIFT_VERSION"
        $SWIFTENV_ROOT/shims/swift build
    - name: Test
      run: $SWIFTENV_ROOT/shims/swift test
