name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        # Build using only Swift 5.3
        # TODO: Update to stable
        swift: ['https://swift.org/builds/swift-5.3-branch/ubuntu1804/swift-5.3-DEVELOPMENT-SNAPSHOT-2020-06-16-a/swift-5.3-DEVELOPMENT-SNAPSHOT-2020-06-16-a-ubuntu18.04.tar.gz']
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies with APT
      run: sudo apt-get update && sudo apt-get install libopus-dev libsodium-dev libcairo2-dev libsqlite3-dev
    - name: Install Swiftenv
      run: git clone --depth 1 https://github.com/kylef/swiftenv.git ~/.swiftenv
    - name: Install Swift
      run: ~/.swiftenv/bin/swiftenv install ${{ matrix.swift }}
    - name: Build
      run: ~/.swiftenv/shims/swift build
    - name: Test
      run: ~/.swiftenv/shims/swift test
