name: macOS

on: [push]

jobs:
  build:
    runs-on: macOS-10.15
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies with Homebrew
      run: |
        brew tap vapor/tap
        brew install opus libsodium ctls cairo
    - name: Build
      run: swift build -Xlinker -L/usr/local/lib -Xlinker -lopus -Xcc -I/usr/local/include
    - name: Test
      run: swift test -Xlinker -L/usr/local/lib -Xlinker -lopus -Xcc -I/usr/local/include

