name: macOS

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies with Homebrew
      run: |
        brew tap vapor/tap
        brew install opus libsodium ctls
    - name: Build
      run: swift build
    - name: Test
      run: swift test

